"""Loading the synthetic control library into the database.

Both entry points (FastAPI startup and the Streamlit app) call :func:`bootstrap` before
serving anything, and Streamlit in particular re-runs its script on every interaction.
Seeding therefore has to be *idempotent by construction* rather than by a "have we run
yet?" flag: controls are upserted on their business key ``control_id`` and the demo
project is looked up (by its ``is_demo`` flag, then by name) before being created.
Calling ``bootstrap()`` a hundred times leaves exactly the same rows as calling it once.

:func:`load_demo_evidence` is the one step that is *not* run at start-up: it writes the
synthetic evidence files and ingests them into the demo project, and it runs only when
an auditor asks for the demo.

The library itself lives in ``data/controls/control_library.json`` rather than in code
so that a researcher can edit, extend or replace the control set without touching the
application, and so that the file can be cited as a study artefact. It is entirely
synthetic - see the ``disclaimer`` key inside the file.
"""

from __future__ import annotations

import json
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.config import get_settings
from app.database.base import init_db, session_scope
from app.database.models import AuditProject, Control, EvidenceFile, ProjectControl
from app.schemas.enums import EvidenceType, ProjectStatus, RiskLevel

#: Signature of the optional progress callback accepted by :func:`load_demo_evidence`:
#: ``progress(done, total, filename)`` after each file.
ProgressCallback = Callable[[int, int, str], None]

#: Default library filename inside ``settings.controls_dir``.
LIBRARY_FILENAME = "control_library.json"

#: The five controls the demo project is scoped to. These are the controls the
#: evaluation datasets are written against, so the demo project and the experiment
#: harness exercise the same requirements.
MANDATED_CONTROL_REFS: List[str] = [
    "CONTROL-001",
    "CONTROL-002",
    "CONTROL-003",
    "CONTROL-004",
    "CONTROL-005",
]

DEMO_PROJECT_NAME = "Privileged Access Management Audit"
DEMO_AUDIT_AREA = "Identity and Access Management"

#: Who the seed acts as when no default auditor name is configured. Written into
#: ``auditor_name`` and ``uploaded_by`` so the activity trail never shows a blank actor
#: for rows the application created on its own.
DEMO_SEED_ACTOR = "Demo seed"

#: Datasets ingested by :func:`load_demo_evidence`. DATASET-005 and DATASET-006 are
#: excluded on purpose: both describe the *same* control as DATASET-001 under a
#: different condition (005 omits the MFA attribute entirely, 006 shows full
#: compliance), so putting their files in one project would leave three contradictory
#: accounts of CONTROL-001 in the same evidence set. They remain available to the
#: evaluation harness, which gives each dataset an isolated project of its own.
DEMO_DATASET_IDS: List[str] = ["DATASET-001", "DATASET-002", "DATASET-003", "DATASET-004"]

#: Provenance sentence attached to every demo summary. Stated once so both front ends
#: show the same words.
DEMO_EVIDENCE_NOTE = (
    "All evidence in this project is synthetic and was generated by "
    "app.evaluation.generator. It represents no real organisation."
)

#: Columns copied straight from a library entry onto a :class:`Control` row.
_CONTROL_FIELDS = (
    "name",
    "objective",
    "description",
    "risk_addressed",
    "expected_evidence",
    "assessment_criteria",
    "framework_refs",
    "category",
    "control_type",
    "control_frequency",
    "inherent_risk",
    "privilege_level",
    "data_sensitivity",
    "retrieval_keywords",
    "source",
)

_LIST_FIELDS = ("expected_evidence", "assessment_criteria", "framework_refs", "retrieval_keywords")

#: Streamlit reruns and uvicorn workers can enter ``bootstrap`` concurrently on the same
#: SQLite file; the lock keeps a single process from racing itself into an
#: IntegrityError. Cross-process races are still handled defensively below.
_BOOTSTRAP_LOCK = threading.Lock()


def library_path(path: Optional[str] = None) -> Path:
    """Resolve the control library file, defaulting to ``settings.controls_dir``."""
    if path:
        return Path(path).expanduser()
    return Path(get_settings().controls_dir) / LIBRARY_FILENAME


def load_control_library(path: Optional[str] = None) -> List[Dict[str, Any]]:
    """Read and normalise the synthetic control library.

    Accepts either the documented ``{"disclaimer": ..., "controls": [...]}`` shape or a
    bare list, so a researcher can drop in a trimmed file without ceremony. Normalising
    here (rather than in the DB layer) means every consumer - seeding, the query builder,
    the report - sees clean types: lists are lists of non-empty strings, the two 1-5
    scores are clamped integers, and ``inherent_risk`` is a valid :class:`RiskLevel`.
    """
    target = library_path(path)
    if not target.exists():
        raise FileNotFoundError(f"Control library not found at {target}")

    with target.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)

    if isinstance(payload, dict):
        raw_controls = payload.get("controls", [])
    elif isinstance(payload, list):
        raw_controls = payload
    else:  # pragma: no cover - malformed file
        raise ValueError(f"Unexpected control library structure in {target}: {type(payload)!r}")

    controls: List[Dict[str, Any]] = []
    seen: Dict[str, int] = {}
    for index, entry in enumerate(raw_controls):
        if not isinstance(entry, dict):
            raise ValueError(f"Control library entry {index} is not an object")
        ref = str(entry.get("control_id", "")).strip()
        if not ref:
            raise ValueError(f"Control library entry {index} has no control_id")
        if ref in seen:
            raise ValueError(f"Duplicate control_id {ref} at entries {seen[ref]} and {index}")
        seen[ref] = index
        controls.append(_normalise_entry(entry, ref))
    return controls


def library_disclaimer(path: Optional[str] = None) -> str:
    """The library's own provenance statement, surfaced in the UI and in reports."""
    target = library_path(path)
    if not target.exists():
        return ""
    with target.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if isinstance(payload, dict):
        return str(payload.get("disclaimer", ""))
    return ""


def _normalise_entry(entry: Dict[str, Any], ref: str) -> Dict[str, Any]:
    out: Dict[str, Any] = dict(entry)
    out["control_id"] = ref
    out["name"] = str(entry.get("name", ref)).strip()
    for key in ("objective", "description", "risk_addressed"):
        out[key] = str(entry.get(key, "") or "").strip()
    for key in _LIST_FIELDS:
        out[key] = _as_str_list(entry.get(key))
    out["category"] = str(entry.get("category", "General") or "General").strip()
    out["control_type"] = str(entry.get("control_type", "Preventive") or "Preventive").strip()
    out["control_frequency"] = str(entry.get("control_frequency", "Continuous") or "Continuous").strip()
    out["inherent_risk"] = RiskLevel.coerce(entry.get("inherent_risk"), RiskLevel.MEDIUM).value
    out["privilege_level"] = _clamp_score(entry.get("privilege_level"), default=3)
    out["data_sensitivity"] = _clamp_score(entry.get("data_sensitivity"), default=3)
    out["source"] = str(entry.get("source", "synthetic-library") or "synthetic-library").strip()
    out["is_active"] = bool(entry.get("is_active", True))
    return out


def _as_str_list(value: Any) -> List[str]:
    if value is None:
        return []
    if isinstance(value, str):
        text = value.strip()
        return [text] if text else []
    if isinstance(value, (list, tuple)):
        return [str(item).strip() for item in value if str(item).strip()]
    return [str(value).strip()]


def _clamp_score(value: Any, default: int = 3) -> int:
    """Keep the 1-5 risk inputs inside the range the prototype risk model assumes."""
    try:
        score = int(value)
    except (TypeError, ValueError):
        return default
    return max(1, min(5, score))


# ---- database seeding
def seed_controls(session: Session, overwrite: bool = False, path: Optional[str] = None) -> int:
    """Upsert the library into the ``controls`` table; return the number of rows written.

    With ``overwrite=False`` (the default) an existing control is left exactly as it is,
    so an auditor's local edits survive a restart and a repeat call writes nothing. With
    ``overwrite=True`` the library file wins and every field is refreshed - that is the
    "reset control library" action, and the only way an edited definition goes back to
    the published one.
    """
    entries = load_control_library(path)
    existing = {
        control.control_id: control
        for control in session.execute(select(Control)).scalars().all()
    }

    written = 0
    for entry in entries:
        control = existing.get(entry["control_id"])
        if control is None:
            session.add(_build_control(entry))
            written += 1
        elif overwrite:
            _apply_entry(control, entry)
            written += 1

    if written:
        try:
            session.commit()
        except IntegrityError:
            # Another process seeded the same rows between the SELECT and the COMMIT.
            # The end state is identical either way, so treat it as a no-op.
            session.rollback()
            return 0
    return written


def _build_control(entry: Dict[str, Any]) -> Control:
    control = Control(control_id=entry["control_id"])
    _apply_entry(control, entry)
    return control


def _apply_entry(control: Control, entry: Dict[str, Any]) -> None:
    for field in _CONTROL_FIELDS:
        setattr(control, field, entry[field])
    control.is_active = entry["is_active"]


def seed_demo_project(session: Session, control_refs: Optional[Sequence[str]] = None) -> AuditProject:
    """Create (or return) the demo audit project, scoping the mandated controls on creation.

    The demo project exists so that the application is not an empty shell on first run:
    a reader of the thesis can start the UI and immediately see a realistic project with
    controls scoped, ready for evidence. Its period is fixed synthetic metadata, not a
    reference to any real engagement.

    The lookup is by ``is_demo`` first and by name second, so renaming the demo project
    in the UI does not make the next start-up create a second one. Controls are scoped
    **only when the row is created**: an auditor who takes a demo control out of scope
    has made a decision about the engagement, and a restart must not quietly reverse it.
    """
    refs = list(control_refs) if control_refs is not None else MANDATED_CONTROL_REFS

    project = _find_demo_project(session)
    if project is not None:
        return project

    project = AuditProject(
        name=DEMO_PROJECT_NAME,
        audit_area=DEMO_AUDIT_AREA,
        description=(
            "Synthetic demonstration audit covering the design and operating "
            "effectiveness of controls over privileged access, account lifecycle, "
            "patching, change approval and password configuration. All data in this "
            "project is fabricated for research purposes."
        ),
        period_start=datetime(2025, 1, 1, tzinfo=timezone.utc),
        period_end=datetime(2025, 6, 30, tzinfo=timezone.utc),
        auditor_name=demo_actor(),
        status=ProjectStatus.FIELDWORK.value,
        scope_note=(
            "Scope limited to the five library controls used by the evaluation "
            "datasets. Synthetic evidence only - no real system was examined."
        ),
        is_demo=True,
    )
    session.add(project)
    try:
        session.commit()
    except IntegrityError:  # pragma: no cover - concurrent bootstrap
        session.rollback()
        existing = _find_demo_project(session)
        if existing is None:
            raise
        return existing

    _scope_refs(session, project, refs)
    return project


def demo_actor() -> str:
    """The actor name the seed writes: the configured auditor, else ``DEMO_SEED_ACTOR``."""
    configured = (get_settings().default_auditor_name or "").strip()
    return configured or DEMO_SEED_ACTOR


def _find_demo_project(session: Session) -> Optional[AuditProject]:
    """The demo project, by flag first and by its seeded name as a fallback.

    Evaluation-harness projects are also flagged ``is_demo`` (they hold synthetic data),
    so the flag lookup excludes anything whose scope note carries the harness marker and
    prefers the oldest match - the row this seed made.
    """
    from app.audit.service import EVALUATION_SCOPE_TAG

    stmt = (
        select(AuditProject)
        .where(AuditProject.is_demo.is_(True))
        .where(
            (AuditProject.scope_note.is_(None))
            | (~AuditProject.scope_note.contains(EVALUATION_SCOPE_TAG))
        )
        .order_by(AuditProject.id.asc())
    )
    project = session.execute(stmt).scalars().first()
    if project is not None:
        return project
    return (
        session.execute(
            select(AuditProject)
            .where(AuditProject.name == DEMO_PROJECT_NAME)
            .order_by(AuditProject.id.asc())
        )
        .scalars()
        .first()
    )


def _scope_refs(session: Session, project: AuditProject, refs: Sequence[str]) -> int:
    """Link the named library controls to ``project``, skipping ones already scoped."""
    controls = (
        session.execute(select(Control).where(Control.control_id.in_(list(refs))))
        .scalars()
        .all()
    )
    by_ref = {control.control_id: control for control in controls}
    already = {
        row.control_id
        for row in session.execute(
            select(ProjectControl).where(ProjectControl.project_id == project.id)
        )
        .scalars()
        .all()
    }

    added = 0
    for ref in refs:
        control = by_ref.get(ref)
        if control is None or control.id in already:
            continue
        session.add(
            ProjectControl(
                project_id=project.id,
                control_id=control.id,
                scope_note="Scoped by demo seed data.",
            )
        )
        added += 1

    if added:
        try:
            session.commit()
        except IntegrityError:  # pragma: no cover - concurrent bootstrap
            session.rollback()
            return 0
    return added


def bootstrap(session: Optional[Session] = None, overwrite: bool = False) -> Dict[str, Any]:
    """Seed controls and the demo project. Safe to call on every application start.

    Pass a ``session`` when the caller already owns one (tests, a FastAPI request, a
    temporary database). With no session this opens its own and also calls
    :func:`init_db`, because the only caller that has no session is an application
    starting from scratch. ``init_db`` is deliberately *not* called when a session is
    supplied: that session may be bound to a different engine, and creating tables on
    the default engine as a side effect would be surprising.
    """
    if session is not None:
        return _bootstrap_with(session, overwrite)

    with _BOOTSTRAP_LOCK:
        init_db()
        with session_scope() as own_session:
            return _bootstrap_with(own_session, overwrite)


def _bootstrap_with(session: Session, overwrite: bool) -> Dict[str, Any]:
    controls_written = seed_controls(session, overwrite=overwrite)
    project = seed_demo_project(session)
    total_controls = session.execute(select(Control)).scalars().all()
    return {
        "controls_written": controls_written,
        "controls_total": len(total_controls),
        "demo_project_id": project.id,
        "demo_project_name": project.name,
        "scoped_control_refs": [
            link.control.control_id for link in project.scoped_controls if link.control is not None
        ],
    }


# ---- demo evidence
def load_demo_evidence(
    session: Session,
    dataset_ids: Optional[Sequence[str]] = None,
    progress: Optional[ProgressCallback] = None,
    uploaded_by: str = "",
) -> Dict[str, Any]:
    """Generate the synthetic datasets and ingest their files into the demo project.

    This is the "Try the demo audit" action. It runs :func:`bootstrap` first so the
    control library and the demo project exist, writes the chosen datasets' files to
    disk (deterministically - the same bytes every time), then ingests each file with
    the evidence type its dataset declares, so retrieval can tell a policy from an
    export. Re-running it adds nothing: a file already ingested into the project under
    the same filename is skipped, so the button is safe to press twice.

    ``progress(done, total, filename)`` is called after each file - ingested, skipped or
    failed - with ``total`` fixed before ingestion starts, so a caller can drive a
    progress bar. One file failing to ingest is recorded under ``failures`` and does not
    stop the rest.

    Nothing here runs a model. Ingestion parses, chunks and embeds the files; every
    assessment still needs an explicit click by the auditor.

    Everything it creates is fabricated for research use. No real system, account or
    person is represented anywhere in it.
    """
    from app.evaluation import datasets as dataset_module
    from app.evidence.service import ingest_file

    seeded = dict(bootstrap(session, overwrite=False))
    project_id = int(seeded["demo_project_id"])
    chosen = [dataset_module.get_dataset(dataset_id).dataset_id for dataset_id in (dataset_ids or DEMO_DATASET_IDS)]
    actor = (uploaded_by or "").strip() or demo_actor()

    # Generate everything first so ``total`` is known before the first callback.
    plan: List[Any] = []  # (dataset, path) pairs in ingestion order
    for dataset_id in chosen:
        dataset = dataset_module.get_dataset(dataset_id)
        for path in dataset_module.generate_dataset(dataset_id):
            plan.append((dataset, path))
    total = len(plan)

    existing = {
        filename
        for filename in session.execute(
            select(EvidenceFile.filename).where(EvidenceFile.project_id == project_id)
        ).scalars()
    }

    ingested: List[Dict[str, Any]] = []
    skipped: List[str] = []
    failures: List[Dict[str, str]] = []
    done = 0
    for dataset, path in plan:
        done += 1
        if path.name in existing:
            skipped.append(path.name)
            _report_progress(progress, done, total, path.name)
            continue
        declared = dataset.file(path.name)
        try:
            record = ingest_file(
                session,
                project_id,
                path.read_bytes(),
                path.name,
                evidence_type=declared.evidence_type if declared else EvidenceType.OTHER,
                description=(
                    "{0} - synthetic evidence generated for {1}.".format(
                        declared.description if declared else "Synthetic artefact",
                        dataset.dataset_id,
                    )
                ),
                uploaded_by=actor,
                is_synthetic=True,
            )
            existing.add(path.name)
            ingested.append(
                {
                    "filename": record.filename,
                    "dataset_id": dataset.dataset_id,
                    "evidence_type": record.evidence_type,
                    "parse_status": record.parse_status,
                    "chunks": int(record.chunk_count),
                }
            )
        except Exception as exc:  # noqa: BLE001 - one bad file must not stop the seed
            session.rollback()
            failures.append({"filename": path.name, "error": str(exc)})
        _report_progress(progress, done, total, path.name)

    return {
        "project_id": project_id,
        "project_name": seeded.get("demo_project_name", ""),
        "controls_total": seeded.get("controls_total", 0),
        "scoped_control_refs": seeded.get("scoped_control_refs", []),
        "datasets": chosen,
        "ingested": ingested,
        "skipped": skipped,
        "failures": failures,
        "note": DEMO_EVIDENCE_NOTE,
    }


def _report_progress(progress: Optional[ProgressCallback], done: int, total: int, filename: str) -> None:
    """Call the progress hook; a failing hook must not abort a half-finished ingest."""
    if progress is None:
        return
    try:
        progress(done, total, filename)
    except Exception:  # noqa: BLE001 - a UI callback is not allowed to break the seed
        pass


__all__ = [
    "DEMO_AUDIT_AREA",
    "DEMO_DATASET_IDS",
    "DEMO_EVIDENCE_NOTE",
    "DEMO_PROJECT_NAME",
    "DEMO_SEED_ACTOR",
    "LIBRARY_FILENAME",
    "MANDATED_CONTROL_REFS",
    "ProgressCallback",
    "bootstrap",
    "demo_actor",
    "library_disclaimer",
    "library_path",
    "load_control_library",
    "load_demo_evidence",
    "seed_controls",
    "seed_demo_project",
]
