"""Generate, preview and download the audit report for an engagement.

The report is the artefact that leaves the tool, so it is also the last place where an
AI proposal could quietly become an audit finding. ``app.audit.report`` prevents that in
the document itself - the AI assessment and the final auditor assessment are printed as
separate sections, and controls nobody has reviewed are listed as pending rather than
counted as conclusions - and this page's job is to keep that visible at the point of
generation: the summary statistics shown beside each report state how many controls were
actually concluded by a human, and the counting basis travels with them.

Previewing rather than only downloading matters for the same reason. A report that is
downloaded unread is a report whose limitations section was never read, and this one has
a limitations section that a reader genuinely needs.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

import streamlit as st

from app.frontend import components, data_access, state, theme

_FORMATS = ("markdown", "html")

_MIME = {"markdown": "text/markdown", "html": "text/html"}

_EXTENSION = {"markdown": "md", "html": "html"}


def _selected_project() -> Optional[int]:
    project_id = state.current_project_id()
    if project_id is not None:
        return project_id
    components.empty_state(
        "No audit project selected",
        "Choose an engagement in the sidebar. A report is always the report of one "
        "engagement, over the controls in its scope.",
    )
    return None


def _render_generator(project_id: int) -> None:
    components.section_header(
        "Generate a report",
        subtitle="Ten mandated sections, with the AI assessment and the auditor's conclusion kept apart.",
    )
    try:
        stats = data_access.dashboard_stats(project_id)
    except data_access.DataAccessError as exc:
        st.error("Could not read the project figures: {0}".format(exc))
        return

    pending = int(stats.get("pending_human_reviews", 0) or 0)
    assessed = int(stats.get("controls_assessed", 0) or 0)
    if assessed == 0:
        st.warning(
            "No control in this engagement has been assessed, so a report generated now "
            "would list every control as not assessed. That is a valid document, but it "
            "is probably not the one you want."
        )
    elif pending:
        st.info(
            "{0} of the assessed control(s) have no auditor decision. They will appear in "
            "the report as pending review and will be excluded from every conclusive "
            "figure in it, which is the correct treatment - not an omission.".format(pending)
        )

    with st.form("report_form"):
        left, right = st.columns([3, 2], gap="medium")
        with left:
            title = st.text_input(
                "Report title (optional)",
                key="report_title",
                placeholder="IT Audit Report - {0}".format(state.current_project_name("")),
                help="Left blank, the generator titles it after the project.",
            )
            generated_by = st.text_input(
                "Generated by",
                value=state.auditor_name(),
                key="report_author",
                help="Recorded on the report. A declared name, not an authenticated identity.",
            )
        with right:
            fmt = st.radio(
                "Format",
                options=list(_FORMATS),
                format_func=lambda value: {"markdown": "Markdown (.md)", "html": "HTML (.html)"}[value],
                key="report_format",
                horizontal=True,
            )
            include_evaluation = st.checkbox(
                "Include the research evaluation appendix",
                key="report_eval",
                help=(
                    "Adds the experiment metrics to the document. Useful for the thesis "
                    "submission; unnecessary for a working paper about the controls."
                ),
            )
        submitted = st.form_submit_button("Generate report", type="primary")

    if not submitted:
        return

    with st.spinner("Building the report…"):
        try:
            report = data_access.generate_report(
                project_id,
                generated_by=generated_by.strip(),
                fmt=fmt,
                title=title.strip(),
                include_evaluation=bool(include_evaluation),
            )
        except data_access.DataAccessError as exc:
            st.error("The report could not be generated: {0}".format(exc))
            return

    state.set_current_report(int(report.get("id")) if report.get("id") is not None else None)
    state.flash(
        "Report #{0} generated ({1}, {2} characters).".format(
            report.get("id"), report.get("format", ""), len(str(report.get("content", "")))
        ),
        "success",
    )
    st.rerun()


def _render_summary(report: Dict[str, Any]) -> None:
    """What the document counts, and on what basis - printed beside the document."""
    stats = dict(report.get("summary_stats") or {})
    if not stats:
        st.caption("This report recorded no summary statistics.")
        return

    components.metric_row(
        [
            {
                "label": "Controls reported",
                "value": stats.get("controls_reported", 0),
                "caption": "{0} in scope, {1} assessed.".format(
                    stats.get("controls_in_scope", 0), stats.get("controls_assessed", 0)
                ),
            },
            {
                "label": "Concluded by an auditor",
                "value": stats.get("controls_concluded_by_auditor", 0),
                "color": theme.HUMAN_COLOR,
                "caption": "{0} still pending review.".format(stats.get("controls_pending_review", 0)),
            },
            {
                "label": "Confirmed deficiencies",
                "value": stats.get("confirmed_deficiencies", 0),
                "color": theme.status_color("POTENTIAL_DEFICIENCY"),
                "caption": "Auditor-confirmed only; AI proposals are not counted.",
            },
            {
                "label": "Confirmed high risk",
                "value": stats.get("confirmed_high_risk_findings", 0),
                "color": theme.risk_color("HIGH"),
                "caption": components.RISK_MODEL_NOTE,
            },
            {
                "label": "Auditor departed from the AI",
                "value": stats.get("controls_status_divergent", 0),
                "color": theme.AI_COLOR,
                "caption": "Status agreement {0}.".format(
                    "n/a"
                    if stats.get("human_ai_status_agreement_rate") is None
                    else "{0:.0%}".format(float(stats["human_ai_status_agreement_rate"]))
                ),
            },
            {
                "label": "Citations in the report",
                "value": stats.get("citations_total", 0),
                "caption": "{0} not verified.".format(stats.get("citations_unverified", 0)),
            },
        ],
        columns=6,
    )

    components.kv_grid(
        {
            "Generated": report.get("generated_at", ""),
            "Generated by": report.get("generated_by", ""),
            "Format": report.get("format", ""),
            "Prompt version": stats.get("prompt_version", ""),
            "Application version": stats.get("app_version", ""),
            "Providers / models": "{0} / {1}".format(
                ", ".join(stats.get("llm_providers", []) or []) or "not recorded",
                ", ".join(stats.get("llm_models", []) or []) or "not recorded",
            ),
            "Experiment conditions": ", ".join(stats.get("experiment_modes", []) or []),
            "Evidence files referenced": "{0} ({1} synthetic)".format(
                stats.get("evidence_files", 0), stats.get("evidence_synthetic_files", 0)
            ),
            "Citation verdicts": ", ".join(
                "{0}: {1}".format(key, value)
                for key, value in (stats.get("citation_verdicts") or {}).items()
            ),
        }
    )
    if stats.get("used_mock_provider"):
        st.warning(
            "At least one assessment in this report was produced by the deterministic "
            "offline provider. " + components.MOCK_PROVIDER_NOTE
        )
    components.note(str(stats.get("counting_basis", "")))
    components.note(str(stats.get("risk_model_label", "")))


def _render_preview(report: Dict[str, Any]) -> None:
    content = str(report.get("content") or "")
    fmt = str(report.get("format") or "markdown")
    if not content:
        st.caption("This report has no stored content.")
        return

    components.ai_disclaimer_banner(
        "This document contains AI-generated assessments. Sections that carry an auditor "
        "conclusion are labelled as such inside the document; everything else is a "
        "proposal awaiting review."
    )
    filename = "{0}_report_{1}.{2}".format(
        str(report.get("title", "audit")).replace(" ", "_")[:60] or "audit",
        report.get("id"),
        _EXTENSION.get(fmt, "txt"),
    )
    components.download_row(
        "Download this report ({0})".format(fmt),
        content,
        filename,
        mime=_MIME.get(fmt, "text/plain"),
        key="report_download",
    )
    if report.get("stored_path"):
        st.caption("Also written to disk by the generator at generation time.")

    if fmt == "html":
        # Rendered inside an isolated frame rather than injected into the page: the
        # document brings its own stylesheet, and evidence text quoted inside it is
        # untrusted input that must not be able to touch the console's own DOM.
        from streamlit.components.v1 import html as embed_html

        embed_html(content, height=720, scrolling=True)
    else:
        with st.container(height=720, border=True):
            # unsafe_allow_html stays off: the report is Markdown, and any HTML inside it
            # came from parsed evidence.
            st.markdown(content)

    with st.expander("View the source of this document", expanded=False):
        st.code(content, language="markdown" if fmt == "markdown" else "html")


def render() -> None:
    components.section_header(
        "Reports",
        subtitle="The working paper this engagement produces, with its limitations attached.",
        eyebrow="Research",
    )
    project_id = _selected_project()
    if project_id is None:
        return

    _render_generator(project_id)

    st.markdown("---")
    try:
        reports = data_access.list_reports(project_id=project_id)
    except data_access.DataAccessError as exc:
        st.error("Could not read the report history: {0}".format(exc))
        return

    components.section_header(
        "Previously generated reports",
        subtitle="{0} report(s) for {1}.".format(len(reports), state.current_project_name()),
    )
    if not reports:
        components.empty_state(
            "No report has been generated for this engagement",
            "Use the form above. Reports are kept, so a figure quoted in a write-up can "
            "always be traced back to the document it came from.",
        )
        return

    table = [
        {
            "id": row.get("id"),
            "title": row.get("title", ""),
            "format": row.get("format", ""),
            "generated_by": row.get("generated_by", ""),
            "generated_at": row.get("generated_at"),
            "content_chars": int(row.get("content_chars", 0) or 0),
            "controls_reported": (row.get("summary_stats") or {}).get("controls_reported", 0),
            "concluded_by_auditor": (row.get("summary_stats") or {}).get(
                "controls_concluded_by_auditor", 0
            ),
            "confirmed_deficiencies": (row.get("summary_stats") or {}).get(
                "confirmed_deficiencies", 0
            ),
        }
        for row in reports
    ]
    components.df_table(
        table,
        columns=[
            "id",
            "title",
            "format",
            "generated_by",
            "generated_at",
            "content_chars",
            "controls_reported",
            "concluded_by_auditor",
            "confirmed_deficiencies",
        ],
        column_config={
            "title": st.column_config.TextColumn("Title", width="large"),
            "format": st.column_config.TextColumn("Format", width="small"),
            "generated_by": st.column_config.TextColumn("Generated by", width="medium"),
            "content_chars": st.column_config.NumberColumn("Characters", width="small", format="%d"),
            "controls_reported": st.column_config.NumberColumn("Controls", width="small", format="%d"),
            "concluded_by_auditor": st.column_config.NumberColumn(
                "Auditor-concluded", width="small", format="%d"
            ),
            "confirmed_deficiencies": st.column_config.NumberColumn(
                "Confirmed deficiencies", width="small", format="%d"
            ),
        },
        key="report_table",
    )

    ids = [int(row["id"]) for row in reports if row.get("id") is not None]
    if not ids:
        return
    current = state.current_report_id()
    if current not in ids:
        current = ids[0]
    labels = {
        int(row["id"]): "#{0} · {1} · {2}".format(
            row["id"], row.get("format", ""), row.get("generated_at", "")
        )
        for row in reports
        if row.get("id") is not None
    }
    # Keyed by the current selection so that a report generated a moment ago is the one
    # shown: with a fixed key Streamlit would return this widget's remembered value and
    # ignore ``index``, leaving the previous report on screen after a generation.
    chosen = st.selectbox(
        "Open a report",
        options=ids,
        index=ids.index(current),
        format_func=lambda value: labels.get(value, str(value)),
        key="report_pick_{0}".format(current),
    )
    if int(chosen) != int(current):
        state.set_current_report(int(chosen))
        st.rerun()
    state.set_current_report(int(current))

    try:
        report = data_access.get_report(int(current))
    except data_access.DataAccessError as exc:
        st.error("Could not load the report: {0}".format(exc))
        return
    if report is None:
        st.warning("That report no longer exists.")
        state.set_current_report(None)
        return

    st.markdown("---")
    components.section_header(
        str(report.get("title", "Audit report")),
        subtitle="Report #{0}, generated {1}".format(report.get("id"), report.get("generated_at", "")),
        eyebrow="Report",
    )
    _render_summary(report)
    st.markdown("")
    _render_preview(report)


render()
