"""Evidence - the files an audit project is based on, and the passages stored from them.

Why the passage browser is the important half of this page
----------------------------------------------------------
A citation in this system points at an ``EvidenceChunk`` - shown to the auditor as a
*passage*: an id, a locator, and the exact text the validator matched a quotation
against. When an auditor checks whether the model quoted the evidence faithfully, *this*
is the ground truth they are checking against - not the original PDF, which the pipeline
never re-reads after ingestion. So the passage browser is not a debugging view. It is
the working paper: it shows every stored passage with its locator, lets the auditor
search inside them, and lets them jump straight to a passage id copied from a citation,
including one that belongs to a different file in the audit project.

What the upload panel reports
-----------------------------
Ingestion can partly fail: a file may store but not parse, parse but produce no passage,
or parse with warnings from the extractor. ``ingest_file`` records all of those on the
row rather than raising, so the upload result here prints one plain line per file with
the passage, page and row counts, and collects every warning in one place. A file that
produced no passage is invisible to retrieval no matter how relevant it looks in the
list, and the auditor needs to be told so at the moment they upload it.

Deleting evidence is an audit-relevant act
------------------------------------------
Deleting a file removes its passages. Citations that pointed at those passages survive
with an unresolved id - the same signal a fabricated citation produces - so the
confirmation says exactly that before the button is enabled.

Why provenance is shouted rather than mentioned
-----------------------------------------------
This repository contains material that reads exactly like organisational evidence and is
not: generated datasets, and historical case studies reconstructed from publicly
documented failure patterns under invented organisation names. Realism is the point of
those files and it is also the risk, because a realistic account listing quoted out of
context becomes a claim about a real company. So provenance is not a discreet metadata
field on this page. It is a column on every row, a banner over the list whenever anything
non-synthetic is present, a full-width banner on the detail view, and a required choice at
upload. ``EvidenceType`` says what an artefact *is*; ``EvidenceProvenance`` says where it
*came from*, and only the second one determines what may be claimed on the strength of it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[3]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from typing import Any, Callable, Dict, List, Optional, Sequence  # noqa: E402

import streamlit as st  # noqa: E402

from app.frontend import components, data_access, state, theme  # noqa: E402
from app.schemas.enums import (  # noqa: E402
    EvidenceProvenance,
    ParseStatus,
    provenance_label,
)

PAGE = "evidence"

#: Fallback when the settings facade cannot be read; the real list comes from
#: ``settings_summary()['limits']['supported_upload_extensions']``.
_FALLBACK_EXTENSIONS = [".csv", ".docx", ".json", ".md", ".pdf", ".txt", ".xls", ".xlsx"]

_PAGE_SIZES = [10, 25, 50, 100]

#: The filter row is only worth its screen space once the list is long enough to need it.
_FILTER_THRESHOLD = 8

#: Key of the file selector. Named because the passage browser has to write it (see
#: ``render``) to follow a citation into a different file.
_SELECT_KEY = "evidence_detail_select"

#: Key of the file table, whose row selection is the primary way of opening a file.
_TABLE_KEY = "evidence_table"

_TABLE_COLUMNS = [
    "filename",
    "evidence_type",
    "provenance",
    "size_kb",
    "uploaded_at",
    "parse_status",
    "page_count",
    "row_count",
    "chunk_count",
]

#: Plain-language wording of each provenance, in the order the upload panel offers them.
#: The default comes first. The wording is the auditor's answer to "where does this file
#: come from?", so it is phrased as an answer rather than as a category name.
_PROVENANCE_CHOICES: List[str] = [
    EvidenceProvenance.SYNTHETIC.value,
    EvidenceProvenance.HISTORICAL_PUBLIC.value,
    EvidenceProvenance.ORGANISATIONAL.value,
]
_PROVENANCE_PLAIN: Dict[str, str] = {
    EvidenceProvenance.SYNTHETIC.value: "Test data generated by this tool",
    EvidenceProvenance.HISTORICAL_PUBLIC.value: "Reconstruction of a publicly documented case",
    EvidenceProvenance.ORGANISATIONAL.value: "Real evidence from the audited organisation",
}
#: Shorter wording for a table cell. Still a phrase a reader cannot mistake, never the
#: stored token.
_PROVENANCE_SHORT: Dict[str, str] = {
    EvidenceProvenance.SYNTHETIC.value: "Test data",
    EvidenceProvenance.HISTORICAL_PUBLIC.value: "Historical reconstruction",
    EvidenceProvenance.ORGANISATIONAL.value: "Real organisational evidence",
}

#: Colour per provenance, chosen against the meaning each one has *in this application*
#: rather than by severity:
#:
#: * SYNTHETIC is the quiet default - it is what almost everything here is, and a warning
#:   that fires on every row is a warning nobody reads.
#: * HISTORICAL_PUBLIC is amber-orange: attention, not error. The file is legitimate, and
#:   the one thing that must never happen is a reader taking it for real evidence.
#: * ORGANISATIONAL is red, which looks backwards until you remember what this prototype
#:   is: no authentication, no access control, no encryption at rest, evidence written to
#:   local disk in the clear. Real audit evidence *here* is a condition to flag, not a
#:   badge of quality.
_PROVENANCE_COLORS = {
    EvidenceProvenance.SYNTHETIC.value: theme.GREY,
    EvidenceProvenance.HISTORICAL_PUBLIC.value: theme.ORANGE,
    EvidenceProvenance.ORGANISATIONAL.value: theme.RED,
}

#: Headline shown on the provenance banner. Deliberately blunt for the reconstruction: it
#: is the sentence a reader must not be able to skim past.
_PROVENANCE_HEADLINES = {
    EvidenceProvenance.SYNTHETIC.value: "SYNTHETIC TEST DATA",
    EvidenceProvenance.HISTORICAL_PUBLIC.value: (
        "SYNTHETIC HISTORICAL RECONSTRUCTION - NOT REAL ORGANISATIONAL EVIDENCE"
    ),
    EvidenceProvenance.ORGANISATIONAL.value: "REAL ORGANISATIONAL EVIDENCE",
}

#: Extra line appended to the banner, saying what the auditor must actually do about it.
_PROVENANCE_ACTIONS = {
    EvidenceProvenance.HISTORICAL_PUBLIC.value: (
        "A finding drawn from this file is a statement about the reconstruction. It is not "
        "a finding about any real organisation and must never be reported as one."
    ),
    EvidenceProvenance.ORGANISATIONAL.value: (
        "This prototype has no authentication, no access control and no encryption at rest, "
        "and it writes evidence to local disk in the clear. Real audit evidence should not "
        "be held here."
    ),
}

#: The one-line gloss of what a passage is. Said once per screen, on the detail view.
_PASSAGE_GLOSS = (
    "A passage is the piece of a file the AI is allowed to quote; every citation points at one."
)


def _read(loader: Callable[[], Any], fallback: Any, what: str) -> Any:
    try:
        return loader()
    except data_access.DataAccessError as exc:
        components.error_with_remedy("Could not load {0}.".format(what), exc)
        return fallback


def _extensions() -> List[str]:
    summary = _read(data_access.settings_summary, {}, "the upload limits")
    limits = dict(summary.get("limits", {}) or {})
    raw = list(limits.get("supported_upload_extensions", []) or _FALLBACK_EXTENSIONS)
    return sorted(str(item).lstrip(".").lower() for item in raw)


def _max_upload_mb() -> Any:
    summary = _read(data_access.settings_summary, {}, "the upload limits")
    return dict(summary.get("limits", {}) or {}).get("max_upload_mb", "?")


def _count(number: Any, singular: str, plural: str = "") -> str:
    value = int(number or 0)
    return "{0} {1}".format(value, singular if value == 1 else (plural or singular + "s"))


# ---- provenance
def _provenance_of(record: Any) -> str:
    """Provenance of one evidence record, defaulting the way the enum defaults.

    A row written before the column existed, or by a transport that does not carry it yet,
    reads as SYNTHETIC rather than as blank. That is the safe direction to be wrong in: an
    artefact under-trusted is a nuisance, an artefact over-trusted is a fabricated audit
    record.
    """
    raw = dict(record or {}).get("provenance")
    return EvidenceProvenance.coerce(raw, EvidenceProvenance.SYNTHETIC).value


def _provenance_banner(value: Any, compact: bool = False) -> None:
    """The full-width provenance disclosure.

    Written as markup rather than as ``st.info``/``st.warning`` because the Streamlit
    callouts all look alike, and this is the one notice on the page that must not read as
    another parser warning. The disclosure sentence comes from
    ``app.schemas.enums.PROVENANCE_LABELS`` so that the console, the reports and the
    database never drift into three different wordings of the same disclaimer.
    """
    resolved = EvidenceProvenance.coerce(value, EvidenceProvenance.SYNTHETIC).value
    color = _PROVENANCE_COLORS[resolved]
    lines = [provenance_label(resolved)]
    action = _PROVENANCE_ACTIONS.get(resolved)
    if action and not compact:
        lines.append(action)
    body = "".join(
        '<div style="margin-top:0.35rem;color:{0};">{1}</div>'.format(
            theme.TEXT_MUTED, components.escape(line)
        )
        for line in lines
    )
    st.markdown(
        '<div style="border:1px solid {border};border-left:4px solid {color};'
        'background:{bg};border-radius:6px;padding:0.7rem 0.9rem;margin:0.35rem 0 0.9rem 0;">'
        '<div style="color:{color};font-weight:700;letter-spacing:0.04em;font-size:0.82rem;">'
        "{headline}</div>{body}</div>".format(
            border=theme.BORDER,
            color=color,
            bg=theme.hex_to_rgba(color, 0.10),
            headline=components.escape(_PROVENANCE_HEADLINES[resolved]),
            body=body,
        ),
        unsafe_allow_html=True,
    )


def _provenance_summary(files: Sequence[Dict[str, Any]]) -> None:
    """Count the audit project's evidence by provenance, and warn about the non-synthetic.

    The counts are always shown; the banner only appears when something other than plain
    synthetic test data is held. An audit mixing a reconstruction with real evidence is
    the case this exists to make impossible to miss.
    """
    counts: Dict[str, int] = {}
    for record in files:
        value = _provenance_of(record)
        counts[value] = counts.get(value, 0) + 1
    if not counts:
        return

    components.badges(
        *[
            components.plain_badge(
                "{0}: {1}".format(_PROVENANCE_SHORT[value], counts[value]),
                _PROVENANCE_COLORS[value],
            )
            for value in _PROVENANCE_CHOICES
            if value in counts
        ]
    )
    for value in (
        EvidenceProvenance.ORGANISATIONAL.value,
        EvidenceProvenance.HISTORICAL_PUBLIC.value,
    ):
        if counts.get(value):
            _provenance_banner(value)


# ---- upload
def _upload_panel(project_id: int, expanded: bool) -> None:
    extensions = _extensions()
    with st.expander("Upload evidence", expanded=expanded):
        # ``clear_on_submit`` matters here: an uploader keeps its files across reruns, so
        # without it the next interaction on the page would ingest the same file again.
        with st.form("evidence_upload_{0}".format(project_id), clear_on_submit=True):
            files = st.file_uploader(
                "Evidence files",
                type=extensions,
                accept_multiple_files=True,
                key="evidence_uploader_{0}".format(project_id),
            )
            st.caption(
                "Accepted: {0} · up to {1} MB each".format(", ".join(extensions), _max_upload_mb())
            )
            # Provenance is a required choice rather than a checkbox default. The
            # disclosure sentence sits under each option because a form does not rerun
            # until it is submitted, so a banner that reacted to the choice could not be
            # drawn here; the coloured banner follows on the upload result instead.
            provenance = st.radio(
                "Where does this file come from?",
                options=_PROVENANCE_CHOICES,
                index=0,
                format_func=lambda value: _PROVENANCE_PLAIN.get(value, str(value)),
                captions=[provenance_label(value) for value in _PROVENANCE_CHOICES],
                key="evidence_upload_provenance_{0}".format(project_id),
            )
            left, right = st.columns([1, 2], gap="small")
            with left:
                types = data_access.evidence_types()
                evidence_type = st.selectbox(
                    "Evidence type",
                    options=types,
                    index=types.index("OTHER") if "OTHER" in types else 0,
                    format_func=lambda value: components.label("evidence_type", value),
                    help="Applied to every file in this upload. It helps the AI tell a policy from a listing.",
                    key="evidence_upload_type_{0}".format(project_id),
                )
            with right:
                description = st.text_input(
                    "Description (optional)",
                    placeholder="What this file is, where it came from, and as at when.",
                    key="evidence_upload_description_{0}".format(project_id),
                )
            submitted = st.form_submit_button("Upload and index", type="primary")

        if submitted:
            _ingest(project_id, files or [], evidence_type, description, provenance)


def _ingest(
    project_id: int,
    files: Sequence[Any],
    evidence_type: str,
    description: str,
    provenance: str,
) -> None:
    if not files:
        st.warning("Choose at least one file before pressing Upload and index.")
        return
    results: List[Dict[str, Any]] = []
    # ``is_synthetic`` is no longer a separate question for the auditor to answer. It is
    # the older boolean that provenance subsumes, and the two must never contradict each
    # other on the same row, so it is derived: anything that did not come from an audited
    # entity is synthetic, whether this project fabricated it or reconstructed it from
    # public history.
    synthetic = provenance != EvidenceProvenance.ORGANISATIONAL.value
    total = len(files)
    with st.status("Uploading {0}...".format(_count(total, "file")), expanded=True) as status:
        for position, item in enumerate(files, start=1):
            name = str(getattr(item, "name", "?"))
            status.update(label="Uploading {0} of {1}: {2}".format(position, total, name))
            try:
                record = data_access.upload_evidence(
                    project_id,
                    item.getvalue(),
                    name,
                    evidence_type=evidence_type,
                    description=str(description or "").strip(),
                    uploaded_by=state.auditor_name() or "Auditor",
                    is_synthetic=synthetic,
                    provenance=provenance,
                )
                results.append(record)
                status.write(
                    "{0} - {1}".format(name, _count(record.get("chunk_count", 0), "passage"))
                )
            except data_access.DataAccessError as exc:
                results.append(
                    {
                        "filename": name,
                        "chunk_count": 0,
                        "parse_error": str(exc),
                        "failed": True,
                        "provenance": provenance,
                    }
                )
                status.write("{0} - not stored".format(name))
        stored = [row for row in results if not row.get("failed")]
        status.update(
            label="Uploaded {0} of {1}".format(len(stored), _count(total, "file")),
            state="complete" if stored else "error",
            expanded=False,
        )

    # The per-file outcome has to survive the rerun that refreshes the table, so it is
    # parked in session state and drawn at the top of the next run.
    state.set_last_ingest(results)
    if stored:
        newest = stored[-1].get("id")
        if newest is not None:
            state.set_current_evidence(int(newest))
    st.rerun()


def _ingest_line(record: Dict[str, Any]) -> None:
    """One plain sentence about what the parser made of one uploaded file."""
    name = str(record.get("filename", "") or "(unnamed file)")
    chunks = int(record.get("chunk_count", 0) or 0)
    if not chunks:
        reason = str(record.get("parse_error") or "the parser produced nothing that can be quoted")
        st.error("{0} - not parsed: {1}".format(name, reason))
        return
    rows = int(record.get("row_count", 0) or 0)
    pages = int(record.get("page_count", 0) or 0)
    if rows:
        detail = "{0} in {1}".format(_count(rows, "row"), _count(chunks, "passage"))
    elif pages:
        detail = "{0} from {1}".format(_count(chunks, "passage"), _count(pages, "page"))
    else:
        detail = _count(chunks, "passage")
    st.success("{0} - parsed, {1}".format(name, detail))


def _ingest_report(results: Sequence[Dict[str, Any]], project_id: int) -> None:
    """The upload outcome, one line per file, and where to go next."""
    for record in results:
        _ingest_line(dict(record))

    # The coloured banner promised by the upload form: once, for the strongest
    # non-synthetic provenance among the files just uploaded.
    provenances = {_provenance_of(record) for record in results}
    for value in (
        EvidenceProvenance.ORGANISATIONAL.value,
        EvidenceProvenance.HISTORICAL_PUBLIC.value,
    ):
        if value in provenances:
            _provenance_banner(value, compact=True)
            break

    warnings: List[str] = []
    for record in results:
        name = str(record.get("filename", "") or "")
        for warning in list((dict(record).get("extra_metadata") or {}).get("warnings", []) or []):
            warnings.append("{0}: {1}".format(name, warning))
    if warnings:
        with st.expander("Parser warnings ({0})".format(len(warnings)), expanded=False):
            for warning in warnings:
                st.write("- " + str(warning))

    stage = _read(lambda: data_access.project_stage(project_id), {}, "the audit's progress")
    if stage.get("stage") == "no_controls":
        components.next_steps(
            [("Add controls to this audit", "views/controls.py", ":material/checklist:")]
        )
    else:
        components.next_steps([("Run assessment", "views/assessments.py", ":material/fact_check:")])


# ---- listing
def _filters() -> Dict[str, Any]:
    left, middle, provenance_column, right = st.columns([2, 2, 2, 3], gap="small")
    with left:
        evidence_type = st.selectbox(
            "Evidence type",
            options=["Any"] + data_access.evidence_types(),
            index=0,
            format_func=lambda value: "Any" if value == "Any" else components.label("evidence_type", value),
            key="evidence_type_filter",
        )
    with middle:
        parse_status = st.selectbox(
            "Parsed",
            options=["Any"] + ParseStatus.values(),
            index=0,
            format_func=lambda value: "Any" if value == "Any" else components.label("parse", value),
            key="evidence_parse_filter",
        )
    with provenance_column:
        provenance = st.selectbox(
            "Where from",
            options=["Any"] + _PROVENANCE_CHOICES,
            index=0,
            format_func=lambda value: "Any" if value == "Any" else _PROVENANCE_SHORT.get(value, str(value)),
            key="evidence_provenance_filter",
            help="Isolate the reconstructed material, or everything that is not it.",
        )
    with right:
        search = st.text_input("Search filenames", key="evidence_search")
    return {
        "evidence_type": None if evidence_type == "Any" else evidence_type,
        "parse_status": None if parse_status == "Any" else parse_status,
        "provenance": None if provenance == "Any" else provenance,
        "search": str(search or "").strip(),
    }


def _by_provenance(
    files: Sequence[Dict[str, Any]], provenance: Optional[str]
) -> List[Dict[str, Any]]:
    """Apply the provenance filter in the page rather than in the query.

    ``data_access.list_evidence`` does not take a provenance argument, and that facade is
    owned elsewhere. Filtering here is correct rather than merely expedient at this scale -
    the list is already one audit project's evidence and is fully in memory - but it would
    need to move into the query if the page ever paginated.
    """
    if not provenance:
        return list(files)
    return [record for record in files if _provenance_of(record) == provenance]


def _evidence_table(files: Sequence[Dict[str, Any]]) -> Any:
    """Draw the file table and return its selection event (or None when empty).

    The table is the selector: a click on a row opens that file below. Cells carry the
    friendly wording rather than the stored token - "Historical reconstruction" reads as a
    warning on its own, whereas "HISTORICAL_PUBLIC" does not.
    """
    rows = []
    for record in files:
        row = dict(record)
        row["provenance"] = _PROVENANCE_SHORT.get(_provenance_of(record), _provenance_of(record))
        row["evidence_type"] = components.label("evidence_type", record.get("evidence_type"))
        row["parse_status"] = components.label("parse", record.get("parse_status"))
        rows.append(row)
    return components.df_table(
        rows,
        columns=_TABLE_COLUMNS,
        column_config={
            "filename": st.column_config.TextColumn("File", width="medium"),
            "evidence_type": st.column_config.TextColumn("Type", width="small"),
            "provenance": st.column_config.TextColumn(
                "Where from",
                width="medium",
                help=(
                    "Where the file came from, as distinct from what it is. A historical "
                    "reconstruction was generated from a publicly documented failure "
                    "pattern under an invented organisation name; it is not any real "
                    "organisation's evidence."
                ),
            ),
            "uploaded_at": st.column_config.DatetimeColumn(
                "Uploaded", width="small", format="D MMM YYYY HH:mm"
            ),
            "parse_status": st.column_config.TextColumn("Parsed", width="small"),
            "page_count": st.column_config.NumberColumn("Pages", width="small", format="%d"),
            "row_count": st.column_config.NumberColumn("Rows", width="small", format="%d"),
            "chunk_count": st.column_config.NumberColumn(
                "Passages",
                width="small",
                format="%d",
                help="Pieces of the file the AI can quote. A file with none cannot be cited.",
            ),
        },
        empty_message="No evidence matches these filters.",
        key=_TABLE_KEY,
        on_select="rerun",
        selection_mode="single-row",
    )


def _table_pick(event: Any, options: Sequence[int]) -> Optional[int]:
    """The file id selected in the table, or None when no row is selected."""
    selection = getattr(event, "selection", None)
    rows = list(getattr(selection, "rows", []) or []) if selection is not None else []
    if not rows:
        return None
    position = int(rows[0])
    return int(options[position]) if 0 <= position < len(options) else None


# ---- detail and passage browser
def _detail(evidence_file_id: int, focus: Optional[int] = None) -> None:
    evidence = _read(
        lambda: data_access.get_evidence(evidence_file_id), None, "the evidence record"
    )
    if not evidence:
        st.warning("That evidence file no longer exists.")
        state.set_current_evidence(None)
        return

    # Above the shared provenance panel rather than inside it: that panel is owned by
    # ``app.frontend.components`` and reports how the file was parsed, while this banner is
    # the declaration of origin and has to be the first thing read on the screen.
    _provenance_banner(_provenance_of(evidence))
    components.evidence_provenance_panel(evidence, show_hash=True)

    warnings = list((evidence.get("extra_metadata") or {}).get("warnings", []) or [])
    if warnings:
        with st.expander("Parser warnings ({0})".format(len(warnings)), expanded=False):
            for warning in warnings:
                st.write("- " + str(warning))

    chunks = _read(
        lambda: data_access.list_chunks(evidence_file_id), [], "the stored passages"
    )
    _chunk_browser(evidence, chunks, focus)
    _delete_panel(evidence)


def _chunk_browser(
    evidence: Dict[str, Any], chunks: Sequence[Dict[str, Any]], focus: Optional[int] = None
) -> None:
    components.section_header(
        "Passages",
        subtitle="Exactly what is stored, and what a citation is checked against.",
        eyebrow="Ground truth",
    )
    st.caption(_PASSAGE_GLOSS)
    if not chunks:
        components.empty_state(
            "Nothing was stored for this file",
            "The parser produced no passage, so no part of this file can be retrieved or "
            "quoted. The parse error is in the panel above.",
        )
        return

    file_id = evidence.get("id")
    source_types = sorted(
        {str(chunk.get("source_type", "")) for chunk in chunks if chunk.get("source_type")}
    )
    jump_key = "evidence_chunk_jump_{0}".format(file_id)
    # A jump that crossed into this file carries the passage id with it. Seeding the
    # widget's key has to happen before the widget exists, which is why it is done here
    # and not where the jump was requested.
    if focus is not None:
        st.session_state[jump_key] = str(focus)

    top = st.columns([3, 2, 1], gap="small")
    with top[0]:
        needle = st.text_input(
            "Search within this file",
            placeholder="A value, a column heading, a phrase from a policy",
            key="evidence_chunk_search_{0}".format(file_id),
        )
    with top[1]:
        kind = st.selectbox(
            "Passage kind",
            options=["Any"] + source_types,
            index=0,
            key="evidence_chunk_kind_{0}".format(file_id),
            help="How the parser produced the passage: a PDF page, a table row range, a table summary…",
        )
    with top[2]:
        st.write("")
        with st.popover("More", width="stretch"):
            target = st.text_input(
                "Jump to passage id",
                placeholder="e.g. 42",
                key=jump_key,
                help="Paste the passage id from a citation. Ids in other files of this audit are found too.",
            )
            page_size = st.selectbox(
                "Per page",
                options=_PAGE_SIZES,
                index=1,
                key="evidence_chunk_page_size_{0}".format(file_id),
            )

    resolved_focus = _resolve_jump(target, chunks)

    filtered = _filter_chunks(chunks, needle, kind)
    if not filtered:
        st.caption(
            "No passage in this file matches that search. {0} stored.".format(
                _count(len(chunks), "passage is", "passages are")
            )
        )
        return

    total_pages = max(1, (len(filtered) + int(page_size) - 1) // int(page_size))
    page_key = "evidence_chunk_page_{0}".format(file_id)
    # A keyed widget ignores its ``value`` argument once session state holds one, so the
    # page has to be moved by writing the key *before* the widget is created - both to
    # follow a jump and to keep a remembered page inside a narrowed result set.
    stored = st.session_state.get(page_key)
    if isinstance(stored, int) and stored > total_pages:
        st.session_state[page_key] = total_pages
    if resolved_focus is not None:
        positions = [
            index
            for index, chunk in enumerate(filtered)
            if int(chunk.get("chunk_id", -1)) == resolved_focus
        ]
        if positions:
            st.session_state[page_key] = positions[0] // int(page_size) + 1
        else:
            st.info(
                "Passage {0} is in this file but is hidden by the search or passage-kind "
                "filter above.".format(resolved_focus)
            )
    page_number = 1
    if total_pages > 1:
        page_number = int(
            st.number_input(
                "Page",
                min_value=1,
                max_value=total_pages,
                value=int(st.session_state.get(page_key, 1) or 1),
                step=1,
                key=page_key,
            )
        )
    st.caption(
        "Showing {0} of {1} stored passage(s), page {2} of {3}.".format(
            len(filtered), len(chunks), page_number, total_pages
        )
    )

    start = (page_number - 1) * int(page_size)
    for chunk in filtered[start : start + int(page_size)]:
        _chunk_card(chunk, needle, resolved_focus)


def _resolve_jump(target: str, chunks: Sequence[Dict[str, Any]]) -> Optional[int]:
    """Resolve a passage id typed by the auditor, following it into another file if needed."""
    text = str(target or "").strip()
    if not text:
        return None
    if not text.isdigit():
        st.warning("A passage id is a whole number, as printed on a citation.")
        return None
    chunk_id = int(text)
    if any(int(chunk.get("chunk_id", -1)) == chunk_id for chunk in chunks):
        return chunk_id

    context = _read(
        lambda: data_access.chunk_context(chunk_id, window=0), {}, "that passage"
    )
    if not context.get("found"):
        st.warning(
            "No passage {0} exists in this database. A citation pointing at it would be "
            "unresolved - which is exactly what a fabricated citation looks like.".format(chunk_id)
        )
        return None
    other_file = context.get("evidence_file_id")
    st.info(
        "Passage {0} belongs to {1}, not to this file.".format(
            chunk_id, context.get("filename", "another file")
        )
    )
    if other_file is not None and st.button(
        "Open {0}".format(context.get("filename", "that file")),
        key="evidence_chunk_follow_{0}".format(chunk_id),
    ):
        # The file selector for this page was already drawn in this run, and a widget's
        # stored value cannot be changed after it exists. The request is therefore parked
        # and consumed at the top of the next run, before the selector is created. The
        # confirmation is shown there, once the file has actually been opened.
        state.set_filter(PAGE, "pending_open", int(other_file))
        state.set_filter(PAGE, "pending_focus", int(chunk_id))
        state.set_current_evidence(int(other_file))
        st.rerun()
    return None


def _filter_chunks(
    chunks: Sequence[Dict[str, Any]], needle: str, kind: str
) -> List[Dict[str, Any]]:
    text = str(needle or "").strip().lower()
    out: List[Dict[str, Any]] = []
    for chunk in chunks:
        if kind and kind != "Any" and str(chunk.get("source_type", "")) != kind:
            continue
        if text and text not in "{0}\n{1}".format(
            chunk.get("text", ""), chunk.get("locator_text", "")
        ).lower():
            continue
        out.append(chunk)
    return out


def _chunk_card(chunk: Dict[str, Any], needle: str, focus: Optional[int]) -> None:
    chunk_id = int(chunk.get("chunk_id", chunk.get("id", 0)) or 0)
    is_focus = focus is not None and chunk_id == focus
    locator = str(chunk.get("locator_text", "") or "")

    components.badges(
        components.plain_badge("passage {0}".format(chunk_id), theme.ACCENT if is_focus else ""),
        components.plain_badge("index {0}".format(chunk.get("chunk_index", ""))),
        components.plain_badge(str(chunk.get("source_type", ""))),
        components.plain_badge("{0} chars".format(chunk.get("char_count", 0))),
        # Only the in-process transport reports embedding state per passage; over HTTP the
        # per-file count in the provenance panel above is the answer instead.
        components.plain_badge("indexed", theme.GREEN) if chunk.get("has_embedding") else "",
        components.plain_badge("jump target", theme.ACCENT) if is_focus else "",
    )
    # The locator is rendered above the text and in the citation typeface, because it is
    # the part an auditor copies into a working paper.
    st.markdown(
        '<div class="ia-cite-loc" style="margin-bottom:0.25rem;">{0}</div>'.format(
            components.escape(locator or "(no locator recorded)")
        ),
        unsafe_allow_html=True,
    )
    st.markdown(
        '<div class="ia-chunk{focus}">{body}</div>'.format(
            focus=" ia-chunk-focus" if is_focus else "",
            body=_highlight(str(chunk.get("text", "")), needle),
        ),
        unsafe_allow_html=True,
    )


def _highlight(text: str, needle: str) -> str:
    """Escape passage text for HTML, then mark the search term inside it.

    Escaping happens first and the needle is escaped the same way, so the two line up
    and no fragment of an uploaded document can close a tag. Evidence text is untrusted
    input.
    """
    escaped = components.escape(text)
    term = str(needle or "").strip()
    if not term:
        return escaped
    pattern = re.compile(re.escape(components.escape(term)), re.IGNORECASE)
    return pattern.sub(
        lambda match: '<span style="background:{0};color:{1};">{2}</span>'.format(
            theme.hex_to_rgba(theme.ACCENT, 0.28), theme.TEXT, match.group(0)
        ),
        escaped,
    )


def _delete_panel(evidence: Dict[str, Any]) -> None:
    evidence_file_id = int(evidence.get("id"))
    filename = str(evidence.get("filename", ""))
    stored = int(evidence.get("chunks_stored", evidence.get("chunk_count", 0)) or 0)
    with st.expander("Delete this evidence file", expanded=False):
        st.warning(
            "Deleting {0} removes its {1}; any citation that points at this file stops "
            "resolving, and this cannot be undone.".format(filename, _count(stored, "passage"))
        )
        confirm = st.checkbox(
            "I understand that citations into this file will stop resolving.",
            key="evidence_delete_confirm_{0}".format(evidence_file_id),
        )
        if st.button(
            "Delete {0}".format(filename),
            key="evidence_delete_{0}".format(evidence_file_id),
            disabled=not confirm,
        ):
            _delete(evidence_file_id, filename)


def _delete(evidence_file_id: int, filename: str) -> None:
    try:
        removed = data_access.delete_evidence(evidence_file_id)
    except data_access.DataAccessError as exc:
        components.error_with_remedy("Could not delete the file.", exc)
        return
    if removed:
        state.set_current_evidence(None)
    state.flash(
        "Deleted {0} and its passages.".format(filename)
        if removed
        else "That evidence file no longer exists.",
        "success" if removed else "info",
    )
    st.rerun()


# ---- page
def render() -> None:
    components.section_header(
        "Evidence",
        subtitle=(
            "The files this audit is based on. Every quotation in an assessment points back "
            "to a passage stored here."
        ),
        eyebrow="Audit project",
    )
    project_id = state.current_project_id()
    if project_id is None:
        components.empty_state(
            "No audit project selected",
            "Evidence belongs to an audit project. Select one in the sidebar, or start one "
            "on the Audit projects page, before uploading anything.",
        )
        return

    # The outcome of an upload made on the previous run, drawn first so that the auditor
    # reads it before anything else and knows where to go next.
    results = state.take_last_ingest()
    if results:
        _ingest_report([dict(item) for item in results if isinstance(item, dict)], project_id)

    stats = _read(
        lambda: data_access.project_evidence_stats(project_id), {}, "the evidence figures"
    )
    files = _read(lambda: data_access.list_evidence(project_id=project_id), [], "the evidence list")
    unparsed = [row for row in files if not int(row.get("chunk_count", 0) or 0)]
    components.metric_row(
        [
            {"label": "Evidence files", "value": int(stats.get("evidence_files", 0) or 0)},
            {
                "label": "Passages stored",
                "value": int(stats.get("evidence_chunks", 0) or 0),
                "color": theme.ACCENT,
                "caption": "Pieces of the files the AI can quote.",
            },
            {"label": "Total size", "value": "{0} MB".format(stats.get("total_mb", 0.0))},
            {
                "label": "Not retrievable",
                "value": len(unparsed),
                "color": theme.RED if unparsed else theme.GREEN,
                "caption": (
                    "No passage stored, so cannot be quoted: {0}".format(
                        ", ".join(str(row.get("filename")) for row in unparsed)
                    )
                    if unparsed
                    else "Every file produced at least one passage."
                ),
            },
        ],
        columns=4,
    )
    # The compact "Next step" line is drawn by the shell above every Audit page, so this
    # page does not repeat it here.

    # Drawn before the upload panel so that the state of the audit's evidence is read
    # before anything is added to it.
    _provenance_summary(files)
    _upload_panel(project_id, expanded=not files)

    if not files:
        components.empty_state(
            "No evidence in this audit yet",
            "Upload policies, configuration exports, user listings or ticket extracts above. "
            "Nothing can be assessed until there is something to quote.",
        )
        components.next_steps(
            [("Or try the demo audit instead", "views/home.py", ":material/play_arrow:")]
        )
        return

    filtered = list(files)
    if len(files) > _FILTER_THRESHOLD:
        filters = _filters()
        filtered = _by_provenance(
            _read(
                lambda: data_access.list_evidence(
                    project_id=project_id,
                    evidence_type=filters["evidence_type"],
                    parse_status=filters["parse_status"],
                    search=filters["search"],
                ),
                [],
                "the evidence list",
            ),
            filters["provenance"],
        )

    # A "follow this passage into its own file" request from the previous run is applied
    # here, before the selector exists: once a keyed widget has been created, its stored
    # value wins and cannot be changed until the next run. Both halves of the request
    # are consumed together so a stale focus can never attach itself to a later open.
    pending_open = state.get_filter(PAGE, "pending_open", None)
    pending_focus = state.get_filter(PAGE, "pending_focus", None)
    if pending_open is not None or pending_focus is not None:
        state.set_filter(PAGE, "pending_open", None)
        state.set_filter(PAGE, "pending_focus", None)

    visible = filtered or files
    # During a jump the target may be filtered out of the table, so the selector offers
    # every file in the audit rather than only the visible ones.
    if pending_open is not None and int(pending_open) not in {int(row["id"]) for row in visible}:
        visible = list(files)
    options = [int(row["id"]) for row in visible]
    labels = {int(row["id"]): str(row.get("filename", "")) for row in visible}

    event = _evidence_table(filtered)
    picked = _table_pick(event, [int(row["id"]) for row in filtered])
    # The table's selection persists across reruns, so it only counts as a new choice
    # when it differs from the one already acted on; otherwise the selector below wins.
    previous_pick = state.get_filter(PAGE, "table_pick", None)
    state.set_filter(PAGE, "table_pick", picked)

    current = state.current_evidence_id()
    focus: Optional[int] = None
    if pending_open is not None and int(pending_open) in options:
        st.session_state[_SELECT_KEY] = int(pending_open)
        focus = int(pending_focus) if pending_focus is not None else None
        st.success(
            "Opened {0}{1}.".format(
                labels.get(int(pending_open), "the file"),
                " at passage {0}".format(focus) if focus is not None else "",
            )
        )
    elif pending_open is not None:
        st.warning("That file is no longer in this audit, so the passage could not be opened.")
    elif picked is not None and picked != previous_pick and picked in options:
        st.session_state[_SELECT_KEY] = int(picked)
    elif _SELECT_KEY not in st.session_state or st.session_state[_SELECT_KEY] not in options:
        # Seed the selector once, before it exists, instead of passing ``index=`` alongside
        # a key that session state already holds.
        st.session_state[_SELECT_KEY] = current if current in options else options[0]

    st.markdown("---")
    chosen = st.selectbox(
        "Open an evidence file",
        options=options,
        format_func=lambda value: labels.get(value, str(value)),
        key=_SELECT_KEY,
        help="Select a row in the table above, or choose a file here.",
    )
    state.set_current_evidence(int(chosen))
    _detail(int(chosen), focus if int(chosen) == pending_open else None)


if __name__ == "__main__":
    render()
